import { createApp } from 'vue'
// import { createPinia } from 'pinia'
// import router from './router'
import App from './App.vue'

import { OhVueIcon, addIcons } from 'oh-vue-icons'
import {
  BiSnow3,
  FaChevronCircleLeft,
  FaChevronCircleRight,
  FaChevronDown,
  FaChevronLeft,
  FaChevronRight,
  FaChevronUp,
  FaDrum,
  FaFlag,
  FaMapMarker,
  FaPeopleArrows,
  FaPlus,
  FaRegularSave,
  FaSkullCrossbones,
  GiBrain,
  GiBroadsword,
  GiBrokenShield,
  GiCardExchange,
  GiCardPlay,
  GiCatapult,
  GiCrossbow,
  GiCrown,
  GiCrownCoin,
  GiDaemonSkull,
  GiHeartPlus,
  GiHeavyRain,
  GiHood,
  GiMuscleUp,
  GiPadlock,
  GiPocketBow,
  GiSandsOfTime,
  GiScarecrow,
  GiSpy,
  GiStarMedal,
  GiSunflower,
  GiTwoShadows,
  HiChevronLeft,
  HiChevronRight,
  HiSolidEye,
  IoSkull,
  LaCogSolid,
  LaSpinnerSolid,
  LaStarOfLifeSolid,
  MdTouchappRound,
  OiLightBulb,
  OiStack,
  OiStar,
  OiStarFill,
  RiFoggyLine,
} from 'oh-vue-icons/icons'

import './assets/main.css'

addIcons(
  BiSnow3,
  FaChevronCircleLeft,
  FaChevronCircleRight,
  FaChevronDown,
  FaChevronLeft,
  FaChevronRight,
  FaChevronUp,
  FaDrum,
  FaFlag,
  FaMapMarker,
  FaPeopleArrows,
  FaPlus,
  FaRegularSave,
  FaSkullCrossbones,
  GiBrain,
  GiBroadsword,
  GiBrokenShield,
  GiCardExchange,
  GiCardPlay,
  GiCatapult,
  GiCrossbow,
  GiCrown,
  GiCrownCoin,
  GiDaemonSkull,
  GiHeartPlus,
  GiHeavyRain,
  GiHood,
  GiMuscleUp,
  GiPadlock,
  GiPocketBow,
  GiSandsOfTime,
  GiScarecrow,
  GiSpy,
  GiStarMedal,
  GiSunflower,
  GiTwoShadows,
  HiChevronLeft,
  HiChevronRight,
  HiSolidEye,
  IoSkull,
  LaCogSolid,
  LaSpinnerSolid,
  LaStarOfLifeSolid,
  MdTouchappRound,
  OiLightBulb,
  OiStack,
  OiStar,
  OiStarFill,
  RiFoggyLine,
)

const app = createApp(App)
// app.use(createPinia())
// app.use(router)
app.component('v-icon', OhVueIcon)
app.mount('#app')
